### ISSUE TITLE
BChecks concurrent requests?

### ISSUE THREAD

**Issue by Saduff** [PortSwigger/BChecks#116]
Should requests initiated by BChecks run concurrently based on the scan's resource pool configuration? If they should, it's not what I'm observing.

Using the default resource pool with 10 concurrent requests, I can see requests appear in the Logger one by one instead of 10 at once. Additionally, it took 178 seconds (~3 minutes) to issue 188 requests, which seems a bit too long if 10 requests were issued concurrently. I would expect it to finish in under 30 seconds in that case.

**Comment by Michelle-PortSwigger** [comment]
Hi

Can I check a couple of details with you, please? Are you performing a crawl and audit or an audit-only? How many items are in the audit items list for the scan task? Are you scanning 1 item with multiple BChecks?

**Comment by Saduff** [comment]
Hi Michelle!

I'm using the audit-only option with 1 item in the audit items list. And yes, I have multiple BChecks enabled. It seems there's no concurrency either between multiple BChecks or paths in `run for each: potential_path`.

**Comment by Maia-PortSwigger** [comment]
This is expected behaviour. If you had multiple audit items, they would run in parallel, but BChecks run against each audit item are sequential, as are the paths in `run for each: potential_path`.

Thank you for highlighting this. We will be looking at ways to improve speed and performance in this area.
