### ISSUE TITLE
`differs from` not strict

### ISSUE THREAD

**Issue by 0xspade** [PortSwigger/BChecks#136]
I have a bcheck script which has a following line:

`if {base.response.body} differs from {latest.response.body} then`

supposedly, it should only report if there's changes in response body. However, what's happening was there's still a report if there's a change in response headers.

**Comment by Hannah-PortSwigger** [comment]
Hi.

The `{X} differs from {Y}` conditional compares full responses. Even if you provide it with a fragment of a response, like `body`, the diffing will still be done on the full response.

Instead of using this, you should use `not({X} is {Y})`.

We've raised a feature request to adjust the validation to make this distinction clearer.

**Comment by 0xspade** [comment]
This is helpful. I'll try this one.
